os:
 - osx

osx_image:
  # MacOS X 10.15.4
  - xcode11.5
  # MacOS X 10.14.6
  - xcode11.3
  # MacOS X 10.13
  - xcode10.1
  # MacOS X 10.13, Default
  - xcode9.4

language: c
compiler:
  - clang

git:
  submodules: false

notifications:
  email:
    on_success: change
    on_failure: always


before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
        brew update;
        for pkg in openssl autoconf automake autogen libtool nettle p11-kit libtasn1 gettext bison;do
          brew install $pkg || true;
        done;
        for pkg in nettle wget p11-kit libtasn1;do
          brew upgrade $pkg || true;
        done;
    fi

script:
  - export PATH="/usr/local/opt/gettext/bin:$PATH"
  - export PATH="/usr/local/opt/bison/bin:$PATH"
  - ./bootstrap
  - ./configure --disable-full-test-suite --disable-valgrind-tests --disable-doc --disable-guile --disable-dependency-tracking
  - make -j$(sysctl -n hw.ncpu) || make -j$(sysctl -n hw.ncpu) V=1
  - make -j$(sysctl -n hw.ncpu) check gl_public_submodule_commit=

after_failure:
  - find . -name 'test-suite.log' -execdir grep -il "FAILED" {} \; -exec echo {} \; -exec cat {} \;
  - for i in tests/*.log fuzz/*.log;do echo "" && echo $i && cat $i;done
  - cat config.log
